doctrine:
    dbal:
        # url: 'pdo_pgsql://tegia:XkLp2Nma@127.0.0.1:5432/tegia?serverVersion=13'
        url: '%env(resolve:DATABASE_URL)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        # host: '%env(resolve:DATABASE_HOST)%'
        # port: '%env(resolve:DATABASE_PORT)%'
        # charset: '%env(resolve:DATABASE_CHARSET)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false
                prefix: App\Entity
                alias: App
