# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    param_fetcher_listener: true
    # allowed_methods_listener:  true
    # routing_loader: false
    view:
        view_response_listener: true
        formats:
            json: true
    exception:
        enabled: true
        flatten_exception_format: rfc7807
        serializer_error_renderer: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
