version: "3.8"

# Development environment override
services:
    php:
        depends_on:
            - database
        volumes:
            # The "cached" option has no effect on Linux but improves performance on Mac
            - ./:/srv/app:rw,cached
            - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            # If you develop on Mac you can remove the var/ directory from the bind-mount
            # for better performance by enabling the next line 
            # - /srv/app/var
        environment:
            APP_ENV: dev

    caddy:
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./public:/srv/app/public:ro

    ###> symfony/mercure-bundle ###
    ###< symfony/mercure-bundle ###

    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION}-alpine
        env_file:
            - .env
            - .env.local
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            # You should definitely change the password in production
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '5432'
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###

    ###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: [ 1025, 1080 ]
    ###< symfony/mailer ###

volumes:
    ###> doctrine/doctrine-bundle ###
    db-data: null 
    ###< doctrine/doctrine-bundle ###
