api_default:
    resource: ../../src/Controller/
    prefix: /api/v1
    type: annotation

telegram:
    resource: ../../src/Controller/Telegram/
    prefix: /api/v1/telegram
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
